/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User_Contact_Management_App;

import java.awt.Toolkit;

import java.util.Collections;
import java.util.Comparator;
import java.util.LinkedList;
import java.util.Stack;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sourcecodester
 */
public class phonebook extends javax.swing.JFrame {

private LinkedList<Contact> contacts;
Stack<Contact> stack = new Stack<>();

    private void setIconImage() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpg")));
    }

    public class Contact {

        private String name;
        private String phoneNumber;
        private String adress;

        public Contact(String name, String phoneNumber, String adress) {
            this.name = name;
            this.phoneNumber = phoneNumber;
            this.adress = adress;
        }

        public String getName() {
            return name;
        }

        public String getPhoneNumber() {
            return phoneNumber;
        }

        public String getAdress() {
            return adress;
        }
    }

    /**
     * Creates new form User Contact Management App
     */
    public phonebook() {
        contacts = new LinkedList<>();
        initComponents();  
        
        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SAVEbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jb4 = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Contact Management System");
        setBackground(new java.awt.Color(51, 153, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t1.setBackground(new java.awt.Color(153, 255, 153));
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 20, 252, -1));

        t2.setBackground(new java.awt.Color(153, 255, 153));
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 63, 252, -1));

        t3.setBackground(new java.awt.Color(153, 255, 153));
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 103, 252, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Address:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 67, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Phone:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        SAVEbtn.setBackground(new java.awt.Color(0, 255, 255));
        SAVEbtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        SAVEbtn.setForeground(new java.awt.Color(0, 0, 0));
        SAVEbtn.setText("SAVE");
        SAVEbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEbtnActionPerformed(evt);
            }
        });
        getContentPane().add(SAVEbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 137, -1, -1));

        jTable1.setBackground(new java.awt.Color(0, 255, 255));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "Phone"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 178, 471, 214));

        jButton2.setBackground(new java.awt.Color(51, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 137, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 255, 255));
        jButton1.setFont(new java.awt.Font("Sitka Subheading", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("RETRIEVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 137, 100, -1));

        jb4.setBackground(new java.awt.Color(0, 255, 255));
        jb4.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jb4.setForeground(new java.awt.Color(0, 0, 0));
        jb4.setText("SEARCH");
        jb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb4ActionPerformed(evt);
            }
        });
        getContentPane().add(jb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 137, 87, -1));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 138, 81, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User_Contact_Management_App/ara.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void clearFields() {
        t1.setText("");
        t2.setText("");
        t3.setText("");
    }

    public void add() {
        String name = t1.getText().trim();
        String address = t2.getText().trim();
        String phoneNumber = t3.getText().trim();

        if (!name.isEmpty() && !phoneNumber.isEmpty()) {
            Contact contact = new Contact(name,  phoneNumber,address);
            contacts.add(contact);
            updateTable(); 
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this, "Please enter address name and phone number", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void updateTable() {
        Collections.sort(contacts, Comparator.comparing(Contact::getName));
        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
        tblModel.setRowCount(-0);

        for (Contact contact : contacts) {
            tblModel.addRow(new Object[]{contact.getName(), contact.getAdress(), contact.getPhoneNumber()});
        }
    }

    private void deleteContact() {
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow != -1) {
            Contact deletedContact = contacts.remove(selectedRow);
            stack.push(deletedContact);
            updateTable();
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this, "Please select a contact to delete", "Selection Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void retrieveDeletedContact() {
    if (!stack.isEmpty()) {
        Contact retrievedContact = stack.pop();
        contacts.add(retrievedContact);
        updateTable();
        // Optionally, you can also update the deleted table here
    } else {
        JOptionPane.showMessageDialog(this, "No deleted contacts available to retrieve", "Retrieval Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    private void search() {
        String searchName = txtSearch.getText().trim();

        if (!searchName.isEmpty()) {
            txtSearch.setText("");
            for (Contact contact : contacts) {
                if (contact.getName().equalsIgnoreCase(searchName)) {
                    showContact(contact);
                    return;
                }
            }
            JOptionPane.showMessageDialog(this, "Contact not found", "Search Result", JOptionPane.INFORMATION_MESSAGE);
            txtSearch.setText("");
        }
    }
    
       private void showContact(Contact contact) {
        t1.setText(contact.getName());
        t2.setText(contact.getAdress());
        t3.setText(contact.getPhoneNumber());
    }
    
    


    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void SAVEbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEbtnActionPerformed
        add();
    


    }//GEN-LAST:event_SAVEbtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        deleteContact();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed

    }//GEN-LAST:event_t3ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed

    }//GEN-LAST:event_t1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        retrieveDeletedContact();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb4ActionPerformed
        search();
    }//GEN-LAST:event_jb4ActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    /**
     *
     *
     *
     *
     *
     *
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(phonebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(phonebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(phonebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(phonebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new phonebook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SAVEbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jb4;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private static class jTable1Model {

        private static void pop(int selectedIndex) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public jTable1Model() {
        }
    }
}
